DIGITS = '1234567890'
CHAR = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
KEYWORDS = ['SCAN', 'SHOW', 'CHAR', 'INT', 'FLOAT', 'BOOL', 'STRING', 'if','then', 'else', 'REPEAT', 'DO', 'continue', 'break',
            'NOT',
            'AND', 'OR', 'CLASS']
NKEYWORDS = ['class', 'scan', 'show', 'constant', 'char', 'int', 'bool',
             'string', 'repeat', 'do', 'not', 'and', 'or', 'Class', 'Scan', 'Show', 'Constant', 'Char',
             'Int', 'Bool', 'String', 'Repeat', 'Do', 'Not', 'And', 'or']
CONSTANTS = ['PI', 'pi']
RelOPS = ['EE','GT','GTE','LT','LTE','NE']
LogOPS = ['AND','OR','NOT']
OPS = ['PLUS','MINUS','MUL','DIV','MOD','POW']
Paren = [')','(']
CSY = 'COMMENT_SYMBOL'
INT = 'INT CONSTANT'
CHR = 'CHARACTER CONSTANT'
ID = 'IDENTIFIER'
PLUS = 'PLUS'
MINUS = 'MINUS'
DIV = 'DIV'
MUL = 'MUL'
FLOAT = 'FLOAT CONSTANT'
KY = 'KEYWORD'
EQ = 'EQ'
POW = 'POW'
MOD = 'MOD'
BOOL = 'BOOL'
LPAR = '('
RPAR = ')'
LCUR = '{'
RCUR = '}'
DEL = 'DELIMITERS'
NL = 'NEWLINE'
CON = 'CONSTANT'
EE = 'EE'
LT = 'LT'
GT = 'GT'
LTE = 'LTE'
GTE = 'GTE'
STRNG = 'STRING CONSTANT'
NE = 'NE'
N = 'NOT'
COM = 'COMMENT'
OP = 'OPERATOR'
ROP = 'RELATIONAL OPERATOR'
desc1 = 'INTEGER DATA TYPE'
desc2 = 'FLOAT DATA TYPE'
desc3 = 'INTEGER CONSTANT VALUE'
desc4 = 'INPUT STATEMENT'
desc5 = 'OUTPUT STATEMENT'
desc6 = 'CHARACTER DATA TYPE'
desc7 = 'BOOLEAN DATA TYPE'
desc8 = 'STRING DATA TYPE'
desc9 = 'CONDITIONAL STATEMENT'
desc10 = 'LOOP STATEMENT'
desc11 = 'JUMP STATEMENTS'
desc12 = 'LOGICAL OPERATOR'
desc13 = 'STRING CONSTANT VALUE'
desc14 = 'FLOAT CONSTANT VALUE'
desc15 = 'CHARACTER CONSTANT VALUE'

EOF = 'EOF'